package main

const (
	// setwebhooks
	SetWebhook = "setWebhook"

	GetMe                           = "getMe"
	SendMessage                     = "sendMessage"
	ForwardMessage                  = "forwardMessage"
	SendPhoto                       = "sendPhoto"
	SendAudio                       = "sendAudio"
	SendDocument                    = "sendDocument"
	SendVideo                       = "sendVideo"
	SendAnimation                   = "sendAnimation"
	SendVoice                       = "sendVoice"
	SendVideoNote                   = "sendVideoNote"
	SendMediaGroup                  = "sendMediaGroup"
	SendLocation                    = "sendLocation"
	EditMessageLiveLocation         = "editMessageLiveLocation"
	StopMessageLiveLocation         = "stopMessageLiveLocation"
	SendVenue                       = "sendVenue"
	SendContact                     = "sendContact"
	SendPoll                        = "sendPoll"
	SendDice                        = "sendDice"
	SendChatAction                  = "sendChatAction"
	GetUserProfilePhotos            = "getUserProfilePhotos"
	GetFile                         = "getFile"
	KickChatMember                  = "kickChatMember"
	UnbanChatMember                 = "unbanChatMember"
	RestrictChatMember              = "restrictChatMember"
	PromoteChatMember               = "promoteChatMember"
	SetChatAdministratorCustomTitle = "setChatAdministratorCustomTitle"
	SetChatPermissions              = "setChatPermissions"
	ExportChatInviteLink            = "exportChatInviteLink"
	SetChatPhoto                    = "setChatPhoto"
	DeleteChatPhoto                 = "deleteChatPhoto"
	SetChatTitle                    = "setChatTitle"
	SetChatDescription              = "setChatDescription"
	PinChatMessage                  = "pinChatMessage"
	UnpinChatMessage                = "unpinChatMessage"
	LeaveChat                       = "leaveChat"
	GetChat                         = "getChat"
	GetChatAdministrators           = "getChatAdministrators"
	GetChatMembersCount             = "getChatMembersCount"
	GetChatMember                   = "getChatMember"
	SetChatStickerSet               = "setChatStickerSet"
	DeleteChatStickerSet            = "deleteChatStickerSet"
	AnswerCallbackQuery             = "answerCallbackQuery"
	SetMyCommands                   = "setMyCommands"
	GetMyCommands                   = "getMyCommands"

	EditMessageText        = "editMessageText"
	EditMessageMedia       = "editMessageMedia"
	EditMessageReplyMarkup = "editMessageReplyMarkup"
	StopPoll               = "stopPoll"
	DeleteMessage          = "deleteMessage"

	// stickers
	SendSticker             = "sendSticker"
	GetStickerSet           = "getStickerSet"
	UploadStickerFile       = "uploadStickerFile"
	CreateNewStickerSet     = "createNewStickerSet"
	AddStickerToSet         = "addStickerToSet"
	SetStickerPositionInSet = "setStickerPositionInSet"
	DeleteStickerFromSet    = "deleteStickerFromSet"
	SetStickerSetThumb      = "setStickerSetThumb"

	// Inline mode
	AnswerInlineQuery = "answerInlineQuery"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
	// getMe             = "getMe"
)
